services:
  game-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: addictive-game-server
    networks:
      - game-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://127.0.0.1:8080/', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Development service with volume mount for live updates
  game-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./app/src/main/assets:/app/game:ro
    restart: unless-stopped
    container_name: addictive-game-dev
    networks:
      - game-network
    profiles:
      - dev

networks:
  game-network:
    driver: bridge